### PR TITLE
Use cleopatra.io

### PR DESCRIPTION
**Pull request by ehsan**

### CODE REVIEW

**Comment by bgirard** [comment]
Good to merge after we fix this. We just need to make sure we don't have the add-on deploying to cleopatra.io and do that instead from the cleopatra deploy script.

**Comment by ehsan** [comment]
> This deploy there should be from the cleopatra script.

What do you mean?

**Comment by bgirard** [comment]
When we make changes to the gecko profiler add-on, we shouldn't need to deploy changes to the website. So I think this diff is not needed. In fact I think that entire script can be removed now that we update from github.

**Comment by bgirard** [comment]
I merged this in. I'm going to delete that script anyways in a future commit.

**Pull request merged**
